apiVersion: v1
kind: Template
labels:
  template: iq-server-persistent-template
metadata:
  name: iq-server-persistent
  annotations:
    description: Sonatype IQ Server persistent template
    tags: ci,nexus,iq-server
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/sonatype/nexus-iq-server:${NEXUS_IQ_VERSION}
      name: ${NEXUS_IQ_VERSION}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      recreateParams:
        timeoutSeconds: 600
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: ${SERVICE_NAME}
            command:
              - "/bin/bash"
              - "-c"
              - "curl -o /tmp/iq-server-functions -s https://raw.githubusercontent.com/kenmoini/openshift-sonatype-nexus/master/scripts/iq-server-functions; source /tmp/iq-server-functions;"
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: CONTEXT_PATH
            value: /
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8070
            protocol: TCP
          - containerPort: 8071
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8070
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MAX_MEMORY}
            requests:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /sonatype-work
            name: ${SERVICE_NAME}-work
          - mountPath: /etc/nexus-iq-server
            name: ${SERVICE_NAME}-config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - name: ${SERVICE_NAME}-work
          persistentVolumeClaim:
            claimName: ${SERVICE_NAME}-pv
        - name: ${SERVICE_NAME}-config-volume
          configMap:
            name: iq-server-config
            items:
            - key: config.yml
              path: config.yml
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:${NEXUS_IQ_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: 8070-tcp
      port: 8070
      protocol: TCP
      targetPort: 8070
    - name: 8071-tcp
      port: 8071
      protocol: TCP
      targetPort: 8071
    selector:
      deploymentconfig: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    port:
      targetPort: 8070-tcp
    to:
      kind: Service
      name: ${SERVICE_NAME}
      weight: 100
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- displayName: Sonatype Nexus IQ Server service name
  name: SERVICE_NAME
  required: true
  value: nexus-iq-server
- displayName: Sonatype Nexus IQ Server version
  name: NEXUS_IQ_VERSION
  required: true
  value: 1.71.0
- description: Volume space available for Sonatype Nexus IQ Server e.g. 512Mi, 2Gi
  displayName: Volume Space for Nexus IQ Server
  name: VOLUME_CAPACITY
  required: true
  value: 5Gi
- description: Max memory allocated to the Nexus IQ Server pod
  displayName: Max Memory
  name: MAX_MEMORY
  required: true
  value: 2Gi
